// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0EFsL5yV48wD9U1o8NPOXs0wvkyBr3RI',
    appId: '1:831204442337:web:74f5607b6f6694cbbff7a0',
    messagingSenderId: '831204442337',
    projectId: 'save-easy2074',
    authDomain: 'save-easy2074.firebaseapp.com',
    storageBucket: 'save-easy2074.appspot.com',
    measurementId: 'G-HC6PX2XCM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwOwL8PQo7O5xs8LiSlam6FHUBkOe1-Ms',
    appId: '1:831204442337:android:1590c33b05dae02bbff7a0',
    messagingSenderId: '831204442337',
    projectId: 'save-easy2074',
    storageBucket: 'save-easy2074.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB1TqEtWJVeZvIhmwAzInc-CHkNqcckII',
    appId: '1:831204442337:ios:107b6346af254ae7bff7a0',
    messagingSenderId: '831204442337',
    projectId: 'save-easy2074',
    storageBucket: 'save-easy2074.appspot.com',
    iosBundleId: 'com.example.saveEasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB1TqEtWJVeZvIhmwAzInc-CHkNqcckII',
    appId: '1:831204442337:ios:bc8bc2f332e53a62bff7a0',
    messagingSenderId: '831204442337',
    projectId: 'save-easy2074',
    storageBucket: 'save-easy2074.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0EFsL5yV48wD9U1o8NPOXs0wvkyBr3RI',
    appId: '1:831204442337:web:929c686dc79fe55abff7a0',
    messagingSenderId: '831204442337',
    projectId: 'save-easy2074',
    authDomain: 'save-easy2074.firebaseapp.com',
    storageBucket: 'save-easy2074.appspot.com',
    measurementId: 'G-RXKPHPM4HV',
  );
}
